// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp9jAtQlQi8ozZFfAvgiZqKKaBYbvUHuE',
    appId: '1:441648751369:web:b96ff05d8073b15148e9d8',
    messagingSenderId: '441648751369',
    projectId: 'atelier4-p-elamri-iir5gx',
    authDomain: 'atelier4-p-elamri-iir5gx.firebaseapp.com',
    storageBucket: 'atelier4-p-elamri-iir5gx.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhZLFrdpieABfBFokaFHl-yV07F8_eRVA',
    appId: '1:441648751369:android:61e469eb120d02b648e9d8',
    messagingSenderId: '441648751369',
    projectId: 'atelier4-p-elamri-iir5gx',
    storageBucket: 'atelier4-p-elamri-iir5gx.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcAKGzvFXv4oAFLYoUilx2J-xcDq0bm9Y',
    appId: '1:441648751369:ios:4eba23c77df4fbfc48e9d8',
    messagingSenderId: '441648751369',
    projectId: 'atelier4-p-elamri-iir5gx',
    storageBucket: 'atelier4-p-elamri-iir5gx.appspot.com',
    iosBundleId: 'com.example.atelier4pelamriiir5g7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcAKGzvFXv4oAFLYoUilx2J-xcDq0bm9Y',
    appId: '1:441648751369:ios:1bf66ff2eca6208948e9d8',
    messagingSenderId: '441648751369',
    projectId: 'atelier4-p-elamri-iir5gx',
    storageBucket: 'atelier4-p-elamri-iir5gx.appspot.com',
    iosBundleId: 'com.example.atelier4pelamriiir5g7.RunnerTests',
  );
}
